# Generated by Django 4.2.7 on 2023-11-04 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Surfsession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=100)),
                ('board', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfsessions', to='surflog.spot')),
            ],
        ),
    ]
